### ISSUE TITLE
Unable To Make Call

### ISSUE THREAD

**Issue by SolomonBier** [jconst/PhoneKit#5]
This was working until recently, now getting:

`PJSIP(1):    pjsua_acc.c  .....Unable to create/send REGISTER: Object is busy (PJSIP_EBUSY) [status=171001]`

`13:18:31.395 ERROR:     [0x106514000] AVAudioSessionUtilities.h:111: GetProperty: AudioSessionGetProperty ('cilt') failed with error: '!siz'`

`13:18:31.396 ERROR:     [0x106514000] AVAudioSessionUtilities.h:124: GetProperty_DefaultToZero: AudioSessionGetProperty ('cilt') failed with error: '!siz'`

`PJSIP(2):    pjsua_acc.c  ...SIP registration failed, status=408 (Request Timeout)
2015-05-31 13:18:53.392 FitSpot[3348:1186674] Did stop listening for connections due to error Generic Error`

**Comment by SolomonBier** [comment]
Apologies @jconst, this was yet another Twillio bug !

**Comment by SidMcLaughlin** [comment]
@SolomonBier I just came across the same issue as you did.  Could you shed some light on how you solved the problem?

>13:18:31.395 ERROR: [0x106514000] AVAudioSessionUtilities.h:111: GetProperty: AudioSessionGetProperty ('cilt') failed with error: '!siz'
>13:18:31.396 ERROR: [0x106514000] AVAudioSessionUtilities.h:124: GetProperty_DefaultToZero: AudioSessionGetProperty ('cilt') failed with error: '!siz'
