### ISSUE TITLE
how can i use with another sip server.

### ISSUE THREAD

**Issue by ismaiI1** [jconst/PhoneKit#6]
i don't want to use Twilio. i want to use another sip server. what must i do?

**Comment by jconst** [comment]
That is a pretty sizable change, so you'll want to fork this repo and add the functionality yourself. The class you'll be making the most changes to would be PKTPhone. That class is the abstraction for the Twilio Client SDK, but there are still some parts of the Twilio SDK API that leak out in PKTPhone's interface, so you'll have to change some other classes as well. Basically anything that starts with a TC needs to be replaced.
